version: "3.7"
services:
    server:
        build: ./server
        container_name: server
        restart: always
        ports:
            - "8000:8000"
            

    database:
        build: ./database
        container_name: database
        restart: always
        environment:
                    MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306

